application: demolumber
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- channel_presence

libraries:
- name: django
  version: "1.2"

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /static
  static_dir: static
- url: /_ah/channel/.*
  script: connection_handler.py
- url: .*
  script: main.py